# Generated by Django 3.2.8 on 2021-10-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditems',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
