# Generated by Django 3.2.8 on 2021-10-12 05:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_auto_20211012_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditems',
            name='favorite',
        ),
        migrations.AddField(
            model_name='fooditems',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
