# Generated by Django 3.2.8 on 2021-10-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_mealnutrients'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditems',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='mealnutrients',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
