# Generated by Django 3.2.8 on 2021-10-12 10:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20211012_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealnutrients',
            name='day',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
