# Generated by Django 3.2.8 on 2021-10-12 11:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_mealnutrients_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealnutrients',
            name='day',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
