# Generated by Django 3.2.8 on 2021-10-13 07:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_mealnutrients_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutrientsTracking',
            fields=[
                ('username', models.CharField(default='', max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('day', models.AutoField(primary_key=True, serialize=False)),
                ('calorie', models.FloatField()),
                ('protein', models.FloatField()),
                ('fat', models.FloatField()),
                ('fiber', models.FloatField()),
            ],
        ),
    ]
