# Generated by Django 3.2.8 on 2021-10-13 13:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='notifications',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
