# Generated by Django 3.2.8 on 2021-10-16 12:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20211015_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('walking', models.FloatField()),
                ('running', models.FloatField()),
                ('cycling', models.FloatField()),
            ],
        ),
    ]
